# Generated by Django 5.0.4 on 2024-05-06 14:33

import django.db.models.deletion
import inputpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_token', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('street_number', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=50)),
                ('suburb', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=4)),
                ('state', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('practitioner_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('primary_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('service_description', models.CharField(max_length=100)),
                ('service_medicare_item_number', models.CharField(max_length=15)),
                ('service_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('salutation', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=1, validators=[inputpage.models.validate_gender])),
                ('contact_number', models.CharField(max_length=15)),
                ('medicare_number', models.CharField(max_length=15)),
                ('address_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputpage.address', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('consultation_time', models.DateField()),
                ('consultation_type', models.CharField(max_length=50)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputpage.patient')),
                ('practitioner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputpage.practitioner')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputpage.service')),
            ],
        ),
    ]
