# Generated by Django 5.0.4 on 2024-05-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_token',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
